version: "3"
services:
  asterisk:
    image: dannmaj/asterisk-configured:v2 #andrius/asterisk:11.25.3
    container_name: asterisk-v2
    ports:
      - "5060:5060/udp"
      - "5060:5060/tcp"
      - "10000-10010:10000-10010/udp"
  erl:
    build: ../Docker
    stdin_open: true # docker run -i
    tty: true        # docker run -t
    container_name: erlang-21.3
    links:
      - asterisk